version: "3.9"

services:
  throttling-integration-1:
    container_name: throttling-integration-1
    build:
      context: ../../throttling/integration
      args:
        PROFILE: docker
    ports:
      - "10000:10000" # server port
    environment:
      TZ: Asia/Seoul

  throttling-integration-2:
    container_name: throttling-integration-2
    build:
      context: ../../throttling/integration
      args:
        PROFILE: docker
    ports:
      - "10001:10000" # server port
    environment:
      TZ: Asia/Seoul

  nginx:
    image: nginx:latest
    platform: linux/amd64 # for M1/M2 Mac
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - throttling-integration-1
      - throttling-integration-2

networks:
  default:
    name: throttling-example
    external: true