version: "3.9"

services:
  throttling-example-1:
    container_name: throttling-example-1
    build:
      context: ../../throttling-example
      args:
        PROFILE: docker
    ports:
      - "10000:10000" # server port
    environment:
      TZ: Asia/Seoul
    expose:
      - "10000" # server port

  throttling-example-2:
    container_name: throttling-example-2
    build:
      context: ../../throttling-example
      args:
        PROFILE: docker
    ports:
      - "10001:10001" # server port
    environment:
      TZ: Asia/Seoul
    expose:
      - "10001" # server port

  nginx:
    image: nginx:latest
    platform: linux/amd64 # for M1/M2 Mac
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - throttling-example-1
      - throttling-example-2

networks:
  default:
    name: throttling-example
    external: true