server:
  port: 10001

spring:
  profiles:
    active:
      - chaos-monkey

chaos:
  monkey:
    enabled: true
    watcher:
      service: true
    assaults:
      latency-active: true

management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true

  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - chaosmonkey
