redis:
  topic:
    circuit-breaker: circuit-breaker-open-events

resilience4j:
  circuitbreaker:
    instances:
      example:
        sliding-window-size: 10
        failure-rate-threshold: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
        max-wait-duration-in-half-open-state:
          seconds: 60
      receiver:
        sliding-window-size: 10
        failure-rate-threshold: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 5
        max-wait-duration-in-half-open-state:
          seconds: 60

server:
  port: 10000
