version: '3.9'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    platform: linux/arm64 # for M1/M2 Mac
    command: [ "--config=/etc/otel-collector.yml" ]
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yml

  loki:
    image: grafana/loki:3.3.1
    platform: linux/arm64 # for M1/M2 Mac
    hostname: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64 # for M1/M2 Mac
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    ports:
      - "3000:3000"
    depends_on:
      - otel-collector
      - tempo
      - loki
      - mimir

  tempo:
    image: grafana/tempo:latest
    platform: linux/arm64 # for M1/M2 Mac
    hostname: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"  # tempo
      - "14317:4317"  # otlp grpc
      - "14318:4318"  # otlp http


  mimir:
    image: grafana/mimir:latest
    platform: linux/arm64 # for M1/M2 Mac
    ports:
      - "9009:9009" # Mimir API 및 UI
    command:
      - -config.file=/etc/mimir/mimir-config.yml
    volumes:
      - ./mimir.yml:/etc/mimir/mimir-config.yml

networks:
  default:
    name: resilience-example
    external: true
