apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      derivedFields:
        -   datasourceUid: tempo
            matcherRegex: traceID
            matcherType: label
            name: Trace ID
            url: $${__value.raw}
            urlDisplayLabel: View Trace
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    apiVersion: 1
    uid: tempo
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: true
        tags:
          - key: service.name
            value: app
        customQuery: true
        query: '{$${__tags}} |="$${__trace.traceId}" '
      serviceMap:
        datasourceUid: prometheus
  - name: Mimir
    type: prometheus
    uid: mimir
    access: proxy
    orgId: 1
    url: http://mimir:9009/prometheus
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      httpMethod: GET
